### PR TITLE
Out of bounds marketplace application

### LINKED ISSUE #29: [High] Reachable panic via index out of bounds in gated-marketplace pallet
# \[High\] Reachable panic via `index out of bounds` in `gated-marketplace` pallet

## Summary

An `index out of bounds` panic can be triggered by a malicious actor calling an extrinsic in the `gated-marketplace` pallet.

## Issue details

The [set\_up\_application](https://github.com/hashed-io/hashed-pallets/blob/f85407cedc35bf264b58e1be713cc14a1f15aa21/pallets/gated-marketplace/src/functions.rs#L798) helper function can be called with input such that `fields.len() > custodian_fields.as_ref().unwrap().1.len()` -- for example, if there are elements in `fields` but not in `custodian_fields.1`.

In such cases, the function will try to access a non-existent index in `custodian_fields.1`, throwing an _index out of bounds_ exception. This causes the runtime to panic and could potentially cause a deny-of-service of the chain.

The helper function is directly reachable from the following extrinsics:

- [pallet\_gated\_marketplace::invite](https://github.com/hashed-io/hashed-pallets/blob/f85407cedc35bf264b58e1be713cc14a1f15aa21/pallets/gated-marketplace/src/lib.rs#L535)
- [pallet\_gated\_marketplace::apply](https://github.com/hashed-io/hashed-pallets/blob/f85407cedc35bf264b58e1be713cc14a1f15aa21/pallets/gated-marketplace/src/lib.rs#L429)
- [pallet\_gated\_marketplace::reapply](https://github.com/hashed-io/hashed-pallets/blob/f85407cedc35bf264b58e1be713cc14a1f15aa21/pallets/gated-marketplace/src/lib.rs#L476)

For example here:

```rust
#[pallet::call_index(3)]
#[pallet::weight(Weight::from_parts(10_000,0) + T::DbWeight::get().writes(1))]
pub fn apply(
	origin: OriginFor<T>,
	marketplace_id: [u8; 32],
	// Getting encoding errors from polkadotjs if an object vector have optional fields
	fields: Fields<T>,
	custodian_fields: Option<CustodianFields<T>>,
) -> DispatchResult {
	let who = ensure_signed(origin)?;

	let (custodian, fields) = Self::set_up_application(fields, custodian_fields);
```

## Risk

Since this can be triggered by a call to an extrinsic, an attacker could cause a validator node to crash by submitting a specific crafted extrinsic and cause them to miss their block authoring slot. This could lead **to a denial-of-service of the whole chain** with only very low cost requirements for the attacker.

## Mitigation

Validate the arguments prior to calling `set_up_application`, e.g., ensure that `custodian_fields.as_ref().unwrap().1.len() == fields.len()` holds before calling the function. Note that this change needs to be applied everywhere `set_up_application` is called.
Alternatively, modify `set_up_application` to gracefully handle errors.

### PR DESCRIPTION
**Pull request by didiermis**
# Validation Fixes and Tests in Gated Marketplace

## Overview

The changes implemented focus on enhancing the gated marketplace pallet by introducing error handling for application setup and enforcing validation checks. The motivation behind these changes is to ensure that applications to the marketplace meet specific criteria, such as having the required fields and adhering to the constraints for custodian relationships. This improvement in validation prevents potential runtime errors and enhances the overall robustness of the marketplace application process.

### Tickets

- [ ] Fix #29

## Implementation notes

The implementation involves modifying the `set_up_application` function to return a `Result` type, enabling the function to handle errors gracefully by leveraging Rust's error handling paradigm. Additional checks are introduced to ensure that:
- The `fields` provided for an application are not empty.
- The number of custodian fields matches the number of application fields when custodians are involved.
- The maximum number of files specified for an application is not exceeded.

These checks are accomplished using the `ensure!` macro for concise assertions and the `.map_err` method to transform errors from the `try_from` method into pallet-specific errors.

Furthermore, corresponding changes are made in the callers of `set_up_application` within the module to handle the `Result` returned by the

## Interesting/controversial decisions

The decision to enforce strict validation at the application setup stage could be seen as restrictive, especially in scenarios where marketplace dynamics might demand more flexibility.

## Test coverage

New tests were added in `tests.rs` to cover scenarios involving the new validations. These include tests for applying without fields, applying with mismatched numbers of fields and custodian fields, and exceeding the maximum allowed fields. The tests verify that the system correctly rejects invalid or incomplete applications, and they help ensure that the validations work as intended.

### CODE REVIEW

File: pallets/gated-marketplace/src/functions.rs [hunk 1]
```diff
@@ -794,6 +795,24 @@ impl<T: Config> Pallet<T> {
...
+	) -> DispatchResult {
+		match custodian_fields {
+			Some(c_fields) => {
+				if fields.len() != c_fields.1.len() {
+					return Err(Error::<T>::InsufficientCustodianFields.into())
+				}
+			}
+			None => {
+				if fields.is_empty() {
+					return Err(Error::<T>::FieldsNotProvided.into())
```
Comment (sebastianmontero) [inline pallets/gated-marketplace/src/functions.rs]: Por que se manda un error cuando el campo es None? Es un caso valido el no tener custodian fields.

File: pallets/gated-marketplace/src/lib.rs [hunk 2]
```diff
@@ -435,6 +439,7 @@ pub mod pallet {
 		) -> DispatchResult {
 			let who = ensure_signed(origin)?;
 
+			Self::validate_fields(&fields, &custodian_fields)?;
```
Comment (sebastianmontero) [inline pallets/gated-marketplace/src/lib.rs]: creo que el metodo validate_fields se deberia de llamar dentro de set_up_application, que es donde se encuentra el codigo que causa el issue

**Review by sebastianmontero — CHANGES_REQUESTED** [review]
Para los PRs que arreglan un issue, primero deberiamos de desarrollar un prueba que descubre el issue, y después desarrollar el codigo que lo arregla, para asegurarnos de que el issue esta arreglado. 
Por lo que veo tambien faltan pruebas para el caso en el que el custodian fields es None, ya que este es un caso valido, y el nuevo metodo de validate_fields lanza un error en este caso, sin embargo todas las pruebas pasan.

File: pallets/gated-marketplace/src/functions.rs (hunk 1 above)
Comment (didiermis) [reply pallets/gated-marketplace/src/functions.rs]: En el caso donde custodian_fields es None, está cubierto en el test `apply_to_marketplace_works`	
```rust
assert_ok!(GatedMarketplace::apply(
			RuntimeOrigin::signed(3),
			m_id,
			create_application_fields(2),
			None
		));
```

File: pallets/gated-marketplace/src/lib.rs (hunk 2 above)
Comment (didiermis) [reply pallets/gated-marketplace/src/lib.rs]: Movi la validación hacia set_up_application y también hice un update en el tipo de retorno para dicha función.

File: pallets/gated-marketplace/src/functions.rs (hunk 1 above)
Comment (didiermis) [reply pallets/gated-marketplace/src/functions.rs]: Eliminé la función validate_fields y moví la lógica a la función set_up_application debido a que cambié el tipo de retorno de ésta última. La razón inicial de separarlo fue que una devolvía un dipatchresult y la otra una tupla.

File: pallets/gated-marketplace/src/tests.rs [hunk 3]
```diff
@@ -273,6 +300,60 @@ fn apply_with_custodian_works() {
 	});
 }
 
+#[test]
+fn apply_with_mismatched_number_of_files_and_custodian_files_shouldnt_work() {
```
Comment (sebastianmontero) [inline pallets/gated-marketplace/src/tests.rs]: Nada mas para mantener la consistencia cambiaria "files" por "fields" en el nombre de la prueba

File: pallets/gated-marketplace/src/tests.rs [hunk 4]
```diff
@@ -273,6 +300,60 @@ fn apply_with_custodian_works() {
...
+				create_application_fields(2),
+				create_custodian_fields(4, 1)
+			),
+			Error::<Test>::InsufficientCustodianFields
+		);
+	});
+}
+
+#[test]
+fn apply_with_custodian_but_no_custodian_files_shouldnt_work() {
```
Comment (sebastianmontero) [inline pallets/gated-marketplace/src/tests.rs]: Nada mas para mantener la consistencia cambiaria "files" por "fields" en el nombre de la prueba

**Review by sebastianmontero — CHANGES_REQUESTED** [review]

File: pallets/gated-marketplace/src/tests.rs (hunk 4 above)
Comment (didiermis) [reply pallets/gated-marketplace/src/tests.rs]: Hecho.

File: pallets/gated-marketplace/src/tests.rs (hunk 3 above)
Comment (sebastianmontero) [reply pallets/gated-marketplace/src/tests.rs]: Falta cambiar el nombre de esta prueba

**Review by sebastianmontero — CHANGES_REQUESTED** [review]

**Review by sebastianmontero — APPROVED** [review]
