### PR TITLE
Fix/unsafe arithmetics

### LINKED ISSUE #31: [Low] Usage of unsafe arithmetics in multiple pallets
# \[Low\] Usage of unsafe arithmetics in multiple pallets

## Summary

Unsafe arithmetic is being used in multiple pallets, which can lead to integer overflows or underflows and cause unexpected results.

## Issue details

We found multiple usages of unsafe arithmetics that we could not confirm to be safe. Details for an example follow:

The function [do\_start\_take\_sell\_order](https://github.com/hashed-io/hashed-pallets/blob/9bfc1529715c6a28b26df44eca6ad478c7ef7ae7/pallets/afloat/src/functions.rs#L472) uses unsafe arithmetics in multiple places, e.g.:

```rust
pub fn do_start_take_sell_order(
    authority: OriginFor<T>,
    order_id: [u8; 32],
    tax_credit_amount: T::Balance,
) -> DispatchResult
where
    <T as pallet_uniques::Config>::ItemId: From<u32>,
{
// ...
    ensure!(
        Self::do_get_afloat_balance(who.clone()) >=
// --> Unsafe multiplication
            offer.price_per_credit * tax_credit_amount.into(),
        Error::<T>::NotEnoughAfloatBalanceAvailable
    );

// ...

// --> Unsafe multiplication
    let total_price: T::Balance = price_per_credit * tax_credit_amount;
```

Since `price_per_credit` is initially set to the `price` argument from the `create_offer` extrinsic parameter, an overflow could likely be triggered.

Additional findings are:

- `afloat` ([do\_start\_take\_sell\_order](https://github.com/hashed-io/hashed-pallets/blob/9bfc1529715c6a28b26df44eca6ad478c7ef7ae7/pallets/afloat/src/functions.rs#L472)): Multiple unsafe multiplications (see also lines below the linked finding)
- `fund-admin` ([do\_calculate\_drawdown\_total\_amount](https://github.com/hashed-io/hashed-pallets/blob/9bfc1529715c6a28b26df44eca6ad478c7ef7ae7/pallets/fund-admin/src/functions.rs#L3150), [do\_calculate\_revenue\_total\_amount](https://github.com/hashed-io/hashed-pallets/blob/9bfc1529715c6a28b26df44eca6ad478c7ef7ae7/pallets/fund-admin/src/functions.rs#L3302)): Usage of unchecked add

## Risk

By triggering an integer overflow, a malicious actor can:

1. Crash the nodes compiled in debug mode with overflow checks enabled
2. On nodes which have overflow checks disabled, unexpected behaviors and logic inconsistencies

## Mitigation

Implement proper integer overflow handling by checking call arguments and using safe arithmetic functions (e.g.: [saturating\_mul](https://doc.rust-lang.org/std/primitive.u32.html#method.saturating_mul), [checked\_mul](https://docs.rs/num/latest/num/trait.CheckedMul.html)).

Hashed is using unsafe arithmetic operations in multiple locations in the source code. We strongly suggest to review the usage of these functions and to migrate to safe arithmetic functions instead.

### PR DESCRIPTION
**Pull request by didiermis**
# Title of changes made: [Fix] Avoiding arithmetic overflows in key scaling operations

## Overview

The primary goal of the changes is to mitigate potential arithmetic overflows while performing some vital scaling operations in the "Afloat" and "Fund-Admin" pallets. The purpose is to ensure the safety of mathematical computations and maintain data integrity across the systems.

This PR adds some "safe" arithmetic functions to add, multiply amounts or perform other arithmetic operations without risking any overflow. Whenever such functions are called, they check if the given operation would result in an overflow. If true, it returns an error before executing the operation.

The changes were mainly targeting the "create_tax_credit()" in the "Afloat" Pallet and "calculate_drawdown_total_amount()" and "calculate_revenue_total_amount()" in the "Fund-Admin" Pallet.

## Tickets

Fix #31

## Implementation notes

The implementation involves two significant changes:

1. Addition of the safe arithmetic functions, "safe_add()" and "safe_multiply_offer()". These functions perform the mathematical operation and check for a potential overflow. If the operation would result in an overflow, they short-circuit and return an `ArithmeticOverflow` error.

2. Integration of the newly
3. created safe arithmetic functions into the existing logic. The safe functions are called before performing mathematical calculations in "create_tax_credit()" in  "Afloat" Pallet and "calculate_drawdown_total_amount()" and "calculate_revenue_total_amount()" in the "Fund-Admin" Pallet. If an overflow is detected, the functions will return an error, stopping the operation and preserving the integrity of the system.

## Interesting/controversial decisions

The changes performed might have some tradeoffs in terms of performance since we are checking for potential arithmetic overflow for each operation. However, these checks are essential to maintain the integrity of the system and avoid any data corruption. Additionally, the checks for overflow should have minimum performance impact since they are straightforward and fast to compute.

## Test coverage

The changes include testing of the newly added functionality. In the "Afloat" pallets, we tested the potential overflow using the "replicate_overflow_for_start_take_sell_order()" function, and in the "Fund-Admin" pallets, we used the "replicate_overflow_for_a_drawdown_submission()" and "replicate_overflow_for_a_revenue_submission()". These tests can effectively detect and prevent any arithmetic overflow during the operations.

## Loose ends

This PR doesn't cover every potential overflow scenario. Other parts of the codebase may also benefit from the addition of similar safe arithmetic operations.

### CODE REVIEW

File: pallets/afloat/src/functions.rs [hunk 1]
```diff
@@ -473,6 +473,9 @@ impl<T: Config> Pallet<T> {
 			offer.tax_credit_amount_remaining >= tax_credit_amount,
 			Error::<T>::NotEnoughTaxCreditsAvailable
 		);
+
+		// check arithmatic overflow
+		Self::safe_multiply_offer(offer.price_per_credit, tax_credit_amount)?;
```
Comment (sebastianmontero) [inline pallets/afloat/src/functions.rs]: Deberiamos de utilizar el resultado de esta operacion, en lugar de hacer la multiplicacion otra vez

File: pallets/afloat/src/functions.rs [hunk 2]
```diff
@@ -933,6 +938,14 @@ impl<T: Config> Pallet<T> {
 			})
 	}
 
+	fn safe_multiply_offer(
```
Comment (sebastianmontero) [inline pallets/afloat/src/functions.rs:938]: La funcion deberia de devolver el resultado, para poder utilizarlo

File: pallets/fund-admin/src/functions.rs [hunk 3]
```diff
@@ -2008,13 +2008,8 @@ impl<T: Config> Pallet<T> {
 
 		// Create revenue transaction id
 		let revenue_transaction_id =
-			(revenue_id, job_eligible_id, project_id, timestamp).using_encoded(blake2_256);
-
-		// Ensure revenue transaction id doesn't exist
-		ensure!(
```
Comment (sebastianmontero) [inline pallets/fund-admin/src/functions.rs:2014]: Por que se elimino este check?

File: pallets/fund-admin/src/functions.rs [hunk 4]
```diff
@@ -3125,6 +3120,11 @@ impl<T: Config> Pallet<T> {
 		Ok(())
 	}
 
+	fn safe_add(a: u64, b: u64) -> DispatchResult {
```
Comment (sebastianmontero) [inline pallets/fund-admin/src/functions.rs]: la funcion debería de devolver el resultado para poder utilizarlo

File: pallets/fund-admin/src/functions.rs [hunk 5]
```diff
@@ -3145,6 +3145,8 @@ impl<T: Config> Pallet<T> {
 				// Get transaction data
 				let transaction_data = TransactionsInfo::<T>::get(transaction_id)
 					.ok_or(Error::<T>::TransactionNotFound)?;
+				// Check arithmetic overflow
+				Self::safe_add(drawdown_total_amount, transaction_data.amount)?;
```
Comment (sebastianmontero) [inline pallets/fund-admin/src/functions.rs]: Deberiamos de utlizar el resultado  de esta operacion, en lugar de hacer la operacion otra vez

File: pallets/fund-admin/src/functions.rs [hunk 6]
```diff
@@ -3298,6 +3300,9 @@ impl<T: Config> Pallet<T> {
 					RevenueTransactionsInfo::<T>::get(revenue_transaction_id)
 						.ok_or(Error::<T>::RevenueTransactionNotFound)?;
 
+				// Check arithmetic overflow
+				Self::safe_add(revenue_total_amount, revenue_transaction_data.amount)?;
```
Comment (sebastianmontero) [inline pallets/fund-admin/src/functions.rs]: Deberiamos de utlizar el resultado de esta operacion, en lugar de hacer la operacion otra vez

**Review by sebastianmontero — CHANGES_REQUESTED** [review]

File: pallets/afloat/src/functions.rs (hunk 1 above)
Comment (didiermis) [reply pallets/afloat/src/functions.rs]: Listo.

File: pallets/afloat/src/functions.rs (hunk 2 above)
Comment (didiermis) [reply pallets/afloat/src/functions.rs:938]: Listo.

File: pallets/fund-admin/src/functions.rs (hunk 3 above)
Comment (didiermis) [reply pallets/fund-admin/src/functions.rs:2014]: Estaba repetido, m{as abajo se vuelve a validar.

File: pallets/fund-admin/src/functions.rs (hunk 4 above)
Comment (didiermis) [reply pallets/fund-admin/src/functions.rs]: Listo.

File: pallets/fund-admin/src/functions.rs (hunk 5 above)
Comment (didiermis) [reply pallets/fund-admin/src/functions.rs]: Listo.

File: pallets/fund-admin/src/functions.rs (hunk 6 above)
Comment (didiermis) [reply pallets/fund-admin/src/functions.rs]: Listo.

File: pallets/afloat/src/functions.rs [hunk 7]
```diff
@@ -485,7 +486,7 @@ impl<T: Config> Pallet<T> {
 
 		let creation_date: u64 = T::Timestamp::now().into();
 		let price_per_credit: T::Balance = offer.price_per_credit.into();
-		let total_price: T::Balance = price_per_credit * tax_credit_amount;
+		let total_price: T::Balance = Self::safe_multiply_offer(price_per_credit, tax_credit_amount)?;
```
Comment (sebastianmontero) [inline pallets/afloat/src/functions.rs]: mover esta sentencia arriba del ensure en la linea 478, para poder utilizar el valor de la variable en el ensure

File: pallets/fund-admin/src/functions.rs (hunk 3 above)
Comment (sebastianmontero) [reply pallets/fund-admin/src/functions.rs:2014]: Ok, movamos el ensure antes de crear el RevenueTransactionData por favor

**Review by sebastianmontero — CHANGES_REQUESTED** [review]

File: pallets/afloat/src/functions.rs (hunk 7 above)
Comment (didiermis) [reply pallets/afloat/src/functions.rs]: Listo.

File: pallets/fund-admin/src/functions.rs (hunk 3 above)
Comment (sebastianmontero) [reply pallets/fund-admin/src/functions.rs:2014]: Falta este cambio

File: pallets/afloat/src/functions.rs (hunk 7 above)
Comment (sebastianmontero) [reply pallets/afloat/src/functions.rs]: Falta este cambio

**Review by sebastianmontero — CHANGES_REQUESTED** [review]
No veo los cambios que habia solicitados

**Review by sebastianmontero — APPROVED** [review]
